//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTSTRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accommodation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public accommodation()
        {
            this.images = new HashSet<image>();
            this.reviews = new HashSet<review>();
            this.rooms = new HashSet<room>();
            this.roomBookings = new HashSet<roomBooking>();
        }
    
        public int accommodationId { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string type { get; set; }
        public Nullable<int> starRating { get; set; }
        public string phoneNumber { get; set; }
        public string email { get; set; }
        public string description { get; set; }
        public string mainImage { get; set; }
        public Nullable<decimal> pricePerNight { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public Nullable<int> personId { get; set; }
    
        public virtual userAccount userAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<image> images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<review> reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room> rooms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roomBooking> roomBookings { get; set; }
    }
}
