//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTSTRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int invoiceId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> roomBookingId { get; set; }
        public Nullable<int> tourBookingId { get; set; }
        public Nullable<int> entertainmentId { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public Nullable<int> personId { get; set; }
    
        public virtual entertainmentBooking entertainmentBooking { get; set; }
        public virtual userAccount userAccount { get; set; }
        public virtual roomBooking roomBooking { get; set; }
        public virtual tourBooking tourBooking { get; set; }
        public virtual userAccount userAccount1 { get; set; }
    }
}
