//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTSTRAVEL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelKTSEntities : DbContext
    {
        public TravelKTSEntities()
            : base("name=TravelKTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<accommodation> accommodations { get; set; }
        public virtual DbSet<entertainment> entertainments { get; set; }
        public virtual DbSet<entertainmentBooking> entertainmentBookings { get; set; }
        public virtual DbSet<entertainmentService> entertainmentServices { get; set; }
        public virtual DbSet<entertainmentType> entertainmentTypes { get; set; }
        public virtual DbSet<image> images { get; set; }
        public virtual DbSet<invoice> invoices { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<room> rooms { get; set; }
        public virtual DbSet<room_Service_Link> room_Service_Link { get; set; }
        public virtual DbSet<roomBooking> roomBookings { get; set; }
        public virtual DbSet<roomService> roomServices { get; set; }
        public virtual DbSet<serviceType> serviceTypes { get; set; }
        public virtual DbSet<statistic> statistics { get; set; }
        public virtual DbSet<tour> tours { get; set; }
        public virtual DbSet<tourBooking> tourBookings { get; set; }
        public virtual DbSet<tourSchedule> tourSchedules { get; set; }
        public virtual DbSet<userAccount> userAccounts { get; set; }
    }
}
