//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTSTRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomBooking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public roomBooking()
        {
            this.invoices = new HashSet<invoice>();
        }
    
        public int roombookingId { get; set; }
        public Nullable<int> accommodationId { get; set; }
        public Nullable<int> roomId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> bookingDate { get; set; }
        public Nullable<System.DateTime> checkInDate { get; set; }
        public Nullable<System.DateTime> checkOutDate { get; set; }
        public Nullable<int> guestCount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public Nullable<int> personId { get; set; }
    
        public virtual accommodation accommodation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invoice> invoices { get; set; }
        public virtual room room { get; set; }
        public virtual userAccount userAccount { get; set; }
        public virtual userAccount userAccount1 { get; set; }
    }
}
