//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTSTRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class roomService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public roomService()
        {
            this.room_Service_Link = new HashSet<room_Service_Link>();
        }
    
        public int roomServiceId { get; set; }
        public string serviceName { get; set; }
        public string description { get; set; }
        public Nullable<decimal> extraCost { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public Nullable<int> personId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<room_Service_Link> room_Service_Link { get; set; }
        public virtual userAccount userAccount { get; set; }
    }
}
