//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTSTRAVEL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistic
    {
        public int statisticId { get; set; }
        public string statisticType { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> totalAmount { get; set; }
        public Nullable<System.DateTime> createdAt { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateEdited { get; set; }
        public Nullable<int> personId { get; set; }
    
        public virtual userAccount userAccount { get; set; }
    }
}
